// Generated by CoffeeScript 1.6.2
(function() {
  var Mediakeys, bindKeyFunctions, click, elements, findDOMelements, fireEvent;

  elements = {
    'grooveshark.com': {
      play: 'play-pause',
      forward: 'play-next',
      back: 'play-prev'
    },
    'rdio.com': {
      play: 'play_pause',
      forward: 'next',
      back: 'prev'
    }
  };

  fireEvent = function(element, event) {
    return console.log(element);
  };

  click = function(element) {
    return fireEvent(element, 'click');
  };

  Mediakeys = {};

  findDOMelements = function(domain) {
    var DOMelements, domID, mediaKey, _ref;

    DOMelements = {};
    _ref = elements[domain];
    for (mediaKey in _ref) {
      domID = _ref[mediaKey];
      DOMelements[mediaKey] = document.getElementById(domID);
    }
    return DOMelements;
  };

  bindKeyFunctions = function(DOMelements) {
    var domElement, mediaKey, _results;

    _results = [];
    for (mediaKey in DOMelements) {
      domElement = DOMelements[mediaKey];
      _results.push(Mediakeys[mediaKey] = function() {
        return click(domElement);
      });
    }
    return _results;
  };

  Mediakeys.init = function(domain) {
    var DOMelements;

    DOMelements = findDOMelements(domain);
    return bindKeyFunctions(DOMelements);
  };

  window.Mediakeys = Mediakeys;

}).call(this);
